"use client";
import { useState,useTransition } from "react";
import { useTranslations } from "next-intl";
import { createAdjustment,updateBatch } from "@/features/inventory/actions";
import { formatDate,formatMoney,formatQuantity } from "@/lib/format";

export type InventoryItem={batch_id:string;fruit:string;supplier:string;mark:string;quality:string|null;size:string;quantity_remaining:number;unit:string;purchase_price_per_unit:number|null;received_at:string};
export type Adjustment={id:string;batch_id:string;adjustment_type:string;quantity:number;reason:string;adjusted_at:string;unit:string};
type Group={fruit:string;unit:string;total:number;items:InventoryItem[]}; type Mode="edit"|"adjust"|null;
const reasons=["spoilage","damage","missing","supplier_return","customer_return","correction_decrease","correction_increase"] as const;

function groupsFor(items:InventoryItem[]){const groups=new Map<string,Group>();for(const item of items){const key=`${item.fruit.toLowerCase()}::${item.unit}`,group=groups.get(key)??{fruit:item.fruit,unit:item.unit,total:0,items:[]};group.total+=Number(item.quantity_remaining);group.items.push(item);groups.set(key,group);}return [...groups.values()].map(group=>({...group,items:group.items.sort((a,b)=>new Date(a.received_at).getTime()-new Date(b.received_at).getTime())}));}
function ageFor(receivedAt:string){return Math.max(0,Math.floor((Date.now()-new Date(receivedAt).getTime())/86400000));}
function ageStyle(days:number){return days>=5?"bg-red-50 text-red-700 ring-red-200":days>=3?"bg-amber-50 text-amber-700 ring-amber-200":"bg-emerald-50 text-emerald-700 ring-emerald-200";}

export function CompactInventory({items,adjustments,locale,currency,timezone}:{items:InventoryItem[];adjustments:Adjustment[];locale:string;currency:string;timezone:string}){const [open,setOpen]=useState<{id:string;mode:Mode}|null>(null);return <div className="space-y-3">{groupsFor(items).map(group=><section key={`${group.fruit}-${group.unit}`} className="overflow-hidden rounded-[18px] border border-[#e1e7e2] bg-white"><header className="flex items-center justify-between bg-[#edf4ef] px-3 py-2.5"><h2 className="font-bold text-[#173f31]">{group.fruit}</h2><span className="text-sm font-bold text-[#216148]">{formatQuantity(group.total,locale,group.unit)}</span></header><div className="divide-y divide-[#eee9df]">{group.items.map(item=><BatchRow key={item.batch_id} item={item} history={adjustments.filter(entry=>entry.batch_id===item.batch_id)} locale={locale} currency={currency} timezone={timezone} mode={open?.id===item.batch_id?open.mode:null} setMode={mode=>setOpen(mode?{id:item.batch_id,mode}:null)}/>)}</div></section>)}</div>;}

function BatchRow({item,history,locale,currency,timezone,mode,setMode}:{item:InventoryItem;history:Adjustment[];locale:string;currency:string;timezone:string;mode:Mode;setMode(mode:Mode):void}){const t=useTranslations("Inventory"),days=ageFor(item.received_at);const details=[item.mark,item.quality||t("notSpecified"),item.size!=="normal"?item.size:""].filter(Boolean).join(" · ");return <div><div className={`flex min-h-16 items-center gap-2 border-l-4 px-3 py-2 ${days>=5?"border-red-400":days>=3?"border-amber-400":"border-emerald-400"}`}><button type="button" onClick={()=>setMode(mode?null:"adjust")} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold">{details}</p><span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold ring-1 ${ageStyle(days)}`}>{days===0?t("fresh"):t("ageDays",{count:days})}</span></div><p className="mt-0.5 truncate text-[11px] text-[#777b73]">{formatDate(item.received_at,locale,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:timezone})}{item.purchase_price_per_unit!=null?` · ${formatMoney(item.purchase_price_per_unit,locale,currency)}/${item.unit}`:` · ${t("pricePending")}`}</p></button><strong className="shrink-0 text-sm text-[#216148]">{formatQuantity(item.quantity_remaining,locale,item.unit)}</strong></div>{mode&&<div className="border-t border-[#eee9df] bg-[#faf8f2] p-3"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setMode("adjust")} className={`min-h-10 rounded-xl text-sm font-bold ${mode==="adjust"?"bg-[#216148] text-white":"bg-white text-[#59625b]"}`}>{t("adjust")}</button><button type="button" onClick={()=>setMode("edit")} className={`min-h-10 rounded-xl text-sm font-bold ${mode==="edit"?"bg-[#216148] text-white":"bg-white text-[#59625b]"}`}>{t("edit")}</button></div>{mode==="edit"?<EditForm item={item} locale={locale} close={()=>setMode(null)}/>:<AdjustmentForm item={item} history={history} locale={locale} timezone={timezone}/>}</div>}</div>;}

function EditForm({item,locale,close}:{item:InventoryItem;locale:string;close():void}){const t=useTranslations("Inventory"),[pending,startTransition]=useTransition(),[message,setMessage]=useState("");function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);startTransition(async()=>{const result=await updateBatch(item.batch_id,locale,form);setMessage(result.message);if(result.ok)close();});}return <form onSubmit={submit} className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs font-bold">{t("remaining")}<input name="quantity_remaining" type="number" inputMode="decimal" min="0" step="0.01" required defaultValue={item.quantity_remaining} className="mt-1 min-h-11 w-full rounded-lg border border-[#d8d2c6] px-3"/></label><label className="text-xs font-bold">{t("buyPrice")}<input name="purchase_price_per_unit" type="number" inputMode="decimal" min="0" step="0.01" defaultValue={item.purchase_price_per_unit??""} className="mt-1 min-h-11 w-full rounded-lg border border-[#d8d2c6] px-3"/></label><label className="text-xs font-bold">{t("quality")}<input name="quality" defaultValue={item.quality??""} className="mt-1 min-h-11 w-full rounded-lg border border-[#d8d2c6] px-3"/></label><label className="text-xs font-bold">{t("size")}<select name="size" defaultValue={item.size} className="mt-1 min-h-11 w-full rounded-lg border border-[#d8d2c6] bg-white px-3"><option value="small">{t("small")}</option><option value="normal">{t("normal")}</option><option value="large">{t("large")}</option></select></label>{message&&<p className="col-span-2 text-xs text-[#216148]">{message}</p>}<button disabled={pending} className="col-span-2 min-h-11 rounded-xl bg-[#216148] text-sm font-bold text-white disabled:opacity-60">{pending?t("saving"):t("save")}</button></form>;}

function AdjustmentForm({item,history,locale,timezone}:{item:InventoryItem;history:Adjustment[];locale:string;timezone:string}){const t=useTranslations("Inventory"),[kind,setKind]=useState<string>("spoilage"),[pending,startTransition]=useTransition(),[message,setMessage]=useState("");function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);form.set("adjustment_type",kind);startTransition(async()=>setMessage((await createAdjustment(item.batch_id,locale,form)).message));}return <><form onSubmit={submit} className="mt-3"><div className="grid grid-cols-3 gap-1.5">{reasons.map(reason=><button key={reason} type="button" onClick={()=>setKind(reason)} className={`min-h-11 rounded-xl px-1 text-[11px] font-bold leading-tight ${kind===reason?"bg-[#216148] text-white":"border border-[#ddd7ca] bg-white text-[#59625b]"}`}>{t(`adjustments.${reason}`)}</button>)}</div><div className="mt-3 flex gap-2"><input aria-label={t("quantity")} name="quantity" type="number" inputMode="decimal" min="0.01" max={kind==="customer_return"||kind==="correction_increase"?undefined:item.quantity_remaining} step="0.01" required placeholder={t("quantity")} className="min-h-11 min-w-0 flex-1 rounded-xl border border-[#d8d2c6] px-3"/><button disabled={pending} className="min-h-11 rounded-xl bg-[#216148] px-4 text-sm font-bold text-white disabled:opacity-60">{pending?t("saving"):t("apply")}</button></div><input name="reason" placeholder={t("noteOptional")} className="mt-2 min-h-10 w-full rounded-xl border border-[#d8d2c6] px-3 text-sm"/>{message&&<p className="mt-2 text-xs text-[#216148]">{message}</p>}</form>{history.length>0&&<div className="mt-3 border-t border-[#e7e1d5] pt-2"><p className="text-[10px] font-bold uppercase tracking-wider text-[#777b73]">{t("history")}</p>{history.slice(0,3).map(entry=><div key={entry.id} className="mt-1 flex justify-between text-xs"><span>{t(`adjustments.${entry.adjustment_type}`)} · {formatDate(entry.adjusted_at,locale,{day:"numeric",month:"short",timeZone:timezone})}</span><b>{formatQuantity(entry.quantity,locale,entry.unit)}</b></div>)}</div>}</>;}
