"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState,useTransition } from "react";
import { useTranslations } from "next-intl";
import { createAdjustment } from "@/features/inventory/actions";
import { closeDay } from "@/features/reports/actions";
import { DailyReportPreview,type DetailedDailyReport,type DailyReportLine } from "@/features/reports/DailyReportPreview";
import { formatMoney,formatQuantity } from "@/lib/format";

type Closing={date:string;sales_transactions:number;sales_revenue:number;gross_profit:number;purchase_value:number;spoilage_loss:number;used_estimates:boolean;closed_at:string};
export function ClosingFlow({report,history,shopName,locale,currency}:{report:DetailedDailyReport;history:Closing[];shopName:string;locale:string;currency:string}){const t=useTranslations("Closing"),router=useRouter(),[pending,startTransition]=useTransition(),[message,setMessage]=useState("");const lines=report.lines??[],groups=totals(lines);
 function finish(allow:boolean){startTransition(async()=>{const result=await closeDay(report.date,locale,allow);setMessage(result.message);if(result.ok)router.refresh();});}
 async function share(){const text=t("shareText",{shop:shopName,date:report.date,sales:formatMoney(report.sales_revenue,locale,currency),profit:formatMoney(report.gross_profit,locale,currency),left:report.closing_batch_count??0});if(navigator.share)await navigator.share({title:`${shopName} · ${report.date}`,text});else await navigator.clipboard.writeText(text);}
 return <div className="space-y-4"><Check title={t("activity")}><div className="grid grid-cols-3 gap-2"><Metric label={t("purchases")} value={String(report.stock_batches_added)}/><Metric label={t("transactions")} value={String(report.sale_count)}/><Metric label={t("sales")} value={formatMoney(report.sales_revenue,locale,currency)}/></div></Check>
 <Check title={t("prices")}><div className={`rounded-xl p-3 text-sm ${report.unpriced_batch_count?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-800"}`}>{report.unpriced_batch_count?t("pricesMissing",{count:report.unpriced_batch_count}):t("pricesReady")}{report.unpriced_batch_count>0&&<Link href={`/${locale}/settlements`} className="ml-2 font-bold underline">{t("fix")}</Link>}</div></Check>
 <Check title={t("remaining")}><div className="divide-y divide-[#eee9df]">{lines.filter(line=>line.closing_quantity>0).map(line=><WasteRow key={line.batch_id} line={line} locale={locale} onSaved={()=>router.refresh()}/>)}</div></Check>
 <Check title={t("profitability")}><div className="space-y-2">{groups.map(group=><div key={group.key} className="grid grid-cols-[1fr_auto_auto] gap-3 rounded-xl bg-[#f6f3ec] px-3 py-2 text-sm"><b>{group.key}</b><span>{formatMoney(group.sales,locale,currency)}</span><span className={group.estimated?"text-amber-700":"text-[#216148]"}>{formatMoney(group.profit,locale,currency)}{group.estimated?"*":""}</span></div>)}</div>{report.spoilage_loss!=null&&<p className="mt-3 text-sm text-red-700">{t("spoilageLoss")}: <b>{formatMoney(report.spoilage_loss,locale,currency)}</b></p>}</Check>
 <DailyReportPreview report={report} shopName={shopName} locale={locale} currency={currency}/><div className="grid grid-cols-2 gap-2 print:hidden"><button type="button" onClick={share} className="min-h-12 rounded-xl border border-[#216148] font-bold text-[#216148]">{t("share")}</button>{report.unpriced_batch_count>0?<button disabled={pending} onClick={()=>finish(true)} className="min-h-12 rounded-xl bg-amber-500 px-2 font-bold text-[#3f2a07]">{t("closeEstimated")}</button>:<button disabled={pending} onClick={()=>finish(false)} className="min-h-12 rounded-xl bg-[#216148] font-bold text-white">{t("close")}</button>}</div>{message&&<p className="rounded-xl bg-[#edf4ef] p-3 text-sm font-bold text-[#216148]">{message}</p>}
 {history.length>0&&<Check title={t("history")}>{history.map(item=><Link key={item.date} href={`/${locale}/shop?tab=reports&generate=1&date=${item.date.slice(0,10)}`} className="flex justify-between border-b border-[#eee9df] py-2 text-sm last:border-0"><span>{item.date.slice(0,10)}{item.used_estimates?" · *":""}</span><b>{formatMoney(item.sales_revenue,locale,currency)}</b></Link>)}</Check>}</div>;}
function WasteRow({line,locale,onSaved}:{line:DailyReportLine;locale:string;onSaved():void}){const t=useTranslations("Closing"),[kind,setKind]=useState<"spoilage"|"damage"|null>(null),[pending,startTransition]=useTransition();function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);form.set("adjustment_type",kind??"spoilage");startTransition(async()=>{const result=await createAdjustment(line.batch_id,locale,form);if(result.ok){setKind(null);onSaved();}});}return <div className="py-2"><div className="flex items-center justify-between gap-2"><span className="min-w-0 truncate text-sm"><b>{line.fruit}</b> · {line.mark}</span><b className="text-sm">{formatQuantity(line.closing_quantity,locale,line.unit)}</b><button onClick={()=>setKind(kind?null:"spoilage")} className="rounded-lg bg-[#f1eee7] px-2 py-1 text-xs font-bold">{t("adjust")}</button></div>{kind&&<form onSubmit={submit} className="mt-2 flex gap-2"><button type="button" onClick={()=>setKind("spoilage")} className={`rounded-lg px-2 text-xs font-bold ${kind==="spoilage"?"bg-red-500 text-white":"bg-white"}`}>{t("spoiled")}</button><button type="button" onClick={()=>setKind("damage")} className={`rounded-lg px-2 text-xs font-bold ${kind==="damage"?"bg-amber-500":"bg-white"}`}>{t("damaged")}</button><input name="quantity" type="number" inputMode="decimal" min="0.01" max={line.closing_quantity} step="0.01" required placeholder={t("quantity")} className="min-h-10 min-w-0 flex-1 rounded-lg border px-2"/><button disabled={pending} className="rounded-lg bg-[#216148] px-3 text-xs font-bold text-white">{t("save")}</button></form>}</div>}
function totals(lines:DailyReportLine[]){const map=new Map<string,{key:string;sales:number;profit:number;estimated:boolean}>();for(const line of lines){const key=`${line.fruit} · ${line.mark}`,v=map.get(key)??{key,sales:0,profit:0,estimated:false};v.sales+=line.sales_revenue;v.profit+=line.gross_profit;v.estimated||=line.profit_is_estimated;map.set(key,v)}return [...map.values()].filter(v=>v.sales>0)}function Check({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[20px] border border-[#e7e1d5] bg-white p-4"><h2 className="mb-3 text-sm font-bold">{title}</h2>{children}</section>}function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f6f3ec] p-2"><small className="text-[#747970]">{label}</small><p className="mt-1 truncate font-bold">{value}</p></div>}
