"use client";
import type { ReactNode } from "react";
import { useTranslations } from "next-intl";
import { formatDate, formatMoney, formatQuantity } from "@/lib/format";

export type DailyReportLine={batch_id:string;fruit:string;mark:string;quality:string;size:string;unit:string;received_at:string;first_sold_at:string|null;last_sold_at:string|null;purchased_quantity:number;purchase_price_per_unit:number|null;purchase_value:number;sold_quantity:number;average_selling_price:number|null;sales_revenue:number;gross_profit:number;closing_quantity:number;profit_is_estimated:boolean;suggested_purchase_price:number|null};
export type DetailedDailyReport={date:string;stock_batches_added:number;purchase_value:number;sale_count:number;sales_revenue:number;gross_profit:number;spoilage_loss:number;estimated_sale_item_count:number;unpriced_batch_count:number;closing_batch_count?:number;lines?:DailyReportLine[]};

export function DailyReportPreview({report,shopName,locale,currency}:{report:DetailedDailyReport;shopName:string;locale:string;currency:string}){
 const t=useTranslations("Report"),lines=report.lines??[];
 return <div className="mt-4"><div className="mb-3 flex items-center justify-between print:hidden"><p className="text-xs font-bold uppercase tracking-wider text-[#747970]">{t("preview")}</p><button type="button" onClick={()=>window.print()} className="min-h-10 rounded-xl border border-[#216148] px-3 text-sm font-bold text-[#216148]">{t("savePdf")}</button></div>
 <article className="report-preview rounded-[24px] border border-[#ddd7ca] bg-white p-4 text-[#20241f] print:border-0 print:p-0"><header className="border-b border-[#ddd7ca] pb-4"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#216148]">Kubera</p><h2 className="mt-1 text-xl font-bold">{shopName}</h2><p className="text-sm text-[#747970]">{t("dailyReportFor",{date:formatDate(`${report.date}T12:00:00Z`,locale,{dateStyle:"long",timeZone:"UTC"})})}</p></header>
 <section className="grid grid-cols-3 gap-2 border-b border-[#ddd7ca] py-4"><Summary label={t("sales")} value={formatMoney(report.sales_revenue,locale,currency)}/><Summary label={report.estimated_sale_item_count?t("estimatedProfit"):t("profit")} value={formatMoney(report.gross_profit,locale,currency)}/><Summary label={t("stockPurchased")} value={formatMoney(report.purchase_value,locale,currency)}/></section>
 <h3 className="mt-4 text-sm font-bold">{t("fruitDetails")}</h3>{lines.length===0?<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{t("detailsUnavailable")}</p>:<div className="mt-2 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse text-left text-xs"><thead><tr className="border-y border-[#ddd7ca] bg-[#f7f4ed]"><Th>{t("fruitMark")}</Th><Th>{t("bought")}</Th><Th>{t("sold")}</Th><Th>{t("revenue")}</Th><Th>{t("profit")}</Th><Th>{t("leftover")}</Th></tr></thead><tbody>{lines.map(line=><tr key={line.batch_id} className="border-b border-[#eee9df] align-top"><Td><b>{line.fruit}</b><span className="block text-[#747970]">{line.mark} · {line.quality||line.size}</span><span className="block text-[#747970]">{t("boughtDate",{date:formatDate(line.received_at,locale,{day:"numeric",month:"short"})})}{line.last_sold_at?` · ${t("soldDate",{date:formatDate(line.last_sold_at,locale,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})})}`:""}</span></Td><Td>{line.purchased_quantity?formatQuantity(line.purchased_quantity,locale,line.unit):"—"}<small className="block text-[#747970]">{line.purchase_price_per_unit!=null?`${formatMoney(line.purchase_price_per_unit,locale,currency)}/${line.unit}`:t("pricePending")}</small></Td><Td>{line.sold_quantity?formatQuantity(line.sold_quantity,locale,line.unit):"—"}<small className="block text-[#747970]">{line.average_selling_price!=null?`${formatMoney(line.average_selling_price,locale,currency)}/${line.unit}`:""}</small></Td><Td>{formatMoney(line.sales_revenue,locale,currency)}</Td><Td>{formatMoney(line.gross_profit,locale,currency)}{line.profit_is_estimated&&<small className="block text-amber-700">{t("estimated")}</small>}</Td><Td><b>{formatQuantity(line.closing_quantity,locale,line.unit)}</b></Td></tr>)}</tbody></table></div>}
 {lines.length>0&&<footer className="mt-4 rounded-xl bg-[#edf4ef] p-3 text-sm"><b>{t("tomorrowStock")}</b><p className="mt-1 text-[#526258]">{t("tomorrowStockHint",{count:report.closing_batch_count??lines.filter(line=>line.closing_quantity>0).length})}</p></footer>}</article></div>;
}
function Summary({label,value}:{label:string;value:string}){return <div><p className="text-[10px] text-[#747970]">{label}</p><p className="mt-1 font-bold">{value}</p></div>}; function Th({children}:{children:ReactNode}){return <th className="px-2 py-2 font-bold">{children}</th>}; function Td({children}:{children:ReactNode}){return <td className="px-2 py-2">{children}</td>};
